skip_tags: true
version: 0.0.0.{build}

clone_depth: 1

image: Visual Studio 2022

before_build:
  - 'git submodule update --init --recursive'
  - 'mklink /D C:\android-sdk "C:\Program Files (x86)\Android\android-sdk"'
  - 'set ANDROID_HOME=C:\android-sdk'
  - 'set JAVA_HOME=C:\Program Files\Java\jdk17'

build_script:
  - gradlew.bat build connectedCheck

artifacts:
  - path: app\build\outputs\apk\nonRoot\Release
    name: unsigned-apk
    type: zip

deploy:
  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: R5LbMHDTqII8hvnYye7N7W2q3EXR6KtL88dMHJ7MPKXC1RFJdXsXoWWDwOR17psa
  artifact: app\build\outputs\apk\nonRoot\Release\unsigned-apk.zip
  draft: false
  prerelease: false
  on:
    branch: master                 
    APPVEYOR_REPO_TAG: false
